### ISSUE TITLE
Install docker-machine

### ISSUE THREAD

**Issue by blankenshipz** [connexio-labs/system-bootstrap#1]
The **docker-machine** binary is used downstream in the `connexio-labs/devbox`, should that software package be installed with the script `script/docker-machine`?

@johnallen3d

**Comment by johnallen3d** [comment]
Yes, that would be good. Do you mind submitting a PR?

**Comment by blankenshipz** [comment]
@johnallen3d I'm missing permissions for this repo! :(

**Comment by johnallen3d** [comment]
Can you follow a more traditional fork to PR workflow?

**Comment by blankenshipz** [comment]
:+1:

**Comment by blankenshipz** [comment]
`docker-machine` has been added
